<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-JuanCarlos_GarciaRendonMartinez/blob/main/Data_Analysis_with_Python_(Mod_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Nombre**: Juan Carlos Garcia Rendon Martinez

**Matrícula**: A01793708

**Materia**: Ciencia y Analitica de Datos

**Profesor**: Bernardo Charles Canales

**Fecha**: 11/10/2022

# Python Packages for Data Science 2:28

Usaremos Pandas, Numpy, SciPy, Matplotlib, Seaborn, Scikit-learn y Statsmodels

# Importing and Exporting Data in Python 4:13
Para leer formatos en Python hay que considerar:

  1) formato:  csv, json, xlsx, etc
  2) Path: Donde se encuentra la información, internet o local

Para importar un CSV *Pandas considera que tiene headers el csv

```
import pandas as pd
df=read_csv("nombre.csv", header = None)
df          #imprime todo
df.head(n)  #imprime los primeros n
df.tail(n)  #imprime los ultimos n

se pueden asignar los nombres a las columnas en caso de no tenerlos. Solo hay que hacer una lista y asignarla a df.columns
```
Para guardar de nuevo el archivo se puede hacer:

```
df.to_csv(path)
```

# Getting Started Analyzing Data in Python 4:14

En general usaremos pandas, que utiliza:
objects:  strings

int64:    int

float64:   numeric with decimals

datetime:  Fechas

*Siempre hay que revisar los tipos de dato para saber qué métodos se pueden usar y evitar errores

Para saber como se distribuye la información podemos usar:


```
df.describe()  #Regresa cuenta, media, desviacion, minimo, maximo y cuartiles
df.describe(include="all")    #Hace que también regrese datos categóricos (strings)
df.info()   #Regresa el top 30 y bottom 30
```

# Lab 1: Introducción

In [15]:
##Lab 1:Introduction
import pandas as pd
import numpy as np

path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"
df = pd.read_csv(path, header=None)

df.head(5)

#1. Check the bottom 10 rows of data frame "df".
df.tail(10)

#Nombrar las columnas
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

df.columns = headers
df.head(10)

df1=df.replace('?',np.NaN)   #Remplazar signos

df=df1.dropna(subset=["price"], axis=0)
df.head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575

In [19]:
#2. Find the name of the columns of the dataframe.
print(df.columns)

df.to_csv("automobile.csv", index=False)

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [27]:
from numpy.lib.shape_base import column_stack
print(df.dtypes)   #Dice que tipo de dato tiene cada columna
df.describe()       #Estadisticas de las columnas numericas
df.describe(include="all")       #Estadisticas de todas las columnas

#3. Selecciona las columnas
df[["length", "compression-ratio"]].describe()

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

           length  compression-ratio
count  201.000000         201.000000
mean   174.200995          10.164279
std     12.322175           4.004965
min    141.100000           7.000000
25%    166.800000           8.600000
50%    173.200000           9.000000
75%    183.500000           9.400000
max    208.100000          23.000000

# Graded Review Questions

In [ ]:
#1. What does CSV stand for?  
 #  Comma separeted values

#2. In the data set, which of the following represents an attribute or feature?
 #  Columnas

#3. What is the name of what we want to predict?
 # Target

#4. What is the command to display the first five rows of a dataframe df?
 # df.head()}

#5. What command do you use to get the data type of each row of the dataframe df?
 # df.dtypes

#6. How do you get a statistical summary of a dataframe df?
 # df.describe()

#7. If you use the method describe() without changing any of the arguments, you will get a statistical summary of all the columns of type "object".
 # False

![image.png]()